---
# Simplified BSD License (see LICENSES/BSD-2-Clause.txt or https://opensource.org/licenses/BSD-2-Clause)
# SPDX-FileCopyrightText: Ansible Project
# SPDX-License-Identifier: BSD-2-Clause

comment:
  behavior: default
  require_changes: false
coverage:
  status:
    patch:
      default:
        target: auto
        threshold: 0%
        base: auto
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
github_checks:
  annotations: false
