---
# Simplified BSD License (see LICENSES/BSD-2-Clause.txt or https://opensource.org/licenses/BSD-2-Clause)
# SPDX-FileCopyrightText: Ansible Project
# SPDX-License-Identifier: BSD-2-Clause

comment: true
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        branches:
          - main
        if_not_found: success
        if_ci_failed: error
        informational: true
        only_pulls: false
github_checks:
  annotations: false
