---
# Simplified BSD License (see LICENSES/BSD-2-Clause.txt or https://opensource.org/licenses/BSD-2-Clause)
# SPDX-FileCopyrightText: Ansible Project
# SPDX-License-Identifier: BSD-2-Clause

changelog_filename_template: ../CHANGELOG
changelog_filename_version_depth: 0
changes_file: changelog.yaml
changes_format: combined
is_other_project: true
keep_fragments: false
mention_ancestor: true
new_plugins_after_name: removed_features
notesdir: fragments
output_formats:
  - md
  - rst
prelude_section_name: release_summary
prelude_section_title: Release Summary
sections:
  - - major_changes
    - Major Changes
  - - minor_changes
    - Minor Changes
  - - breaking_changes
    - Breaking Changes / Porting Guide
  - - deprecated_features
    - Deprecated Features
  - - removed_features
    - Removed Features (previously deprecated)
  - - security_fixes
    - Security Fixes
  - - bugfixes
    - Bugfixes
  - - known_issues
    - Known Issues
use_semantic_versioning: false
title: antsibull-docs -- TypeScript library for processing Ansible documentation markup
