---
# Copyright (c) Ansible Project
# Simplified BSD License (see LICENSES/BSD-2-Clause.txt or https://opensource.org/licenses/BSD-2-Clause)
# SPDX-License-Identifier: BSD-2-Clause

name: Verify REUSE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Run once per week (Friday at 07:00 UTC)
  schedule:
    - cron: '0 7 * * 5'

jobs:
  reuse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v3
