---
# Copyright (c) Ansible Project
# Simplified BSD License (see LICENSES/BSD-2-Clause.txt or https://opensource.org/licenses/BSD-2-Clause)
# SPDX-License-Identifier: BSD-2-Clause

name: TypeScript related checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Run once per week (Friday at 07:00 UTC)
  schedule:
    - cron: '0 7 * * 5'

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Install requirements
        run: npm ci

      - name: Run tests
        run: |
          npm run test:coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v4

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Install requirements
        run: npm ci

      - name: Lint
        run: |
          npm run lint

  format:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Install requirements
        run: npm ci

      - name: Check code formatting
        run: |
          npm run format:check
